apiVersion: v2
name: opencloud
description: OpenCloud (fork oCIS) - chart maison pour georgeop.us
type: application
version: 0.1.0
appVersion: "7.4.0"   # vérifier la dernière release sur github.com/opencloud-eu/opencloud
keywords:
  - opencloud
  - files
  - sync
sources:
  - https://github.com/opencloud-eu/opencloud
